import type {
  InteractiveTutorialChapter,
  InteractiveTutorialStep,
} from "@/app/interactiveTutorial/interactiveTutorialTypes";

const operationsSteps = [
  {
    id: "roster-tab",
    title: "Open Roster",
    instruction: "Open the Roster page from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-roster"]',
  },
  {
    id: "create-student",
    title: "Add a student",
    instruction: "In Students, click + and save a new student.",
    selector: '[data-tutorial-target="create-student-button"]',
  },
  {
    id: "inventory-tab",
    title: "Open Inventory",
    instruction: "Open Inventory from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-inventory"]',
  },
  {
    id: "inventory-materials",
    title: "Open Materials",
    instruction: "Switch Inventory to the Materials subtab.",
    selector: '[data-tutorial-target="inventory-view-materials"]',
  },
  {
    id: "create-material",
    title: "Add material",
    instruction: "Use Add and save one material.",
    selector: '[data-tutorial-target="create-material-button"]',
  },
  {
    id: "material-filter",
    title: "Filter materials",
    instruction: "Apply at least one material filter.",
    selector: '[data-tutorial-target="materials-filter-control"]',
  },
  {
    id: "material-edit",
    title: "Edit a material",
    instruction: "Click any material row to open edit mode.",
    selector: '[data-tutorial-target="edit-material-row"]',
  },
  {
    id: "inventory-parts",
    title: "Open Parts",
    instruction: "Switch Inventory to the Parts subtab.",
    selector: '[data-tutorial-target="inventory-view-parts"]',
  },
  {
    id: "create-part",
    title: "Add part definition",
    instruction: "Use Add and save one part definition.",
    selector: '[data-tutorial-target="create-part-button"]',
  },
  {
    id: "part-search",
    title: "Search parts",
    instruction: "Type in the parts search box.",
    selector: '[data-tutorial-target="parts-search-input"]',
  },
  {
    id: "inventory-purchases",
    title: "Open Purchases",
    instruction: "Switch Inventory to the Purchases subtab.",
    selector: '[data-tutorial-target="inventory-view-purchases"]',
  },
  {
    id: "create-purchase",
    title: "Add purchase request",
    instruction: "Use Add and save one purchase request.",
    selector: '[data-tutorial-target="create-purchase-button"]',
  },
  {
    id: "purchase-sort",
    title: "Sort or filter purchases",
    instruction: "Use the Purchases status control.",
    selector: '[data-tutorial-target="purchases-sort-control"]',
  },
  {
    id: "workflow-tab",
    title: "Open Subsystems",
    instruction: "Open Workflow/Subsystems from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-subsystems"]',
  },
  {
    id: "create-subsystem",
    title: "Create a subsystem",
    instruction: "Use Add subsystem and save it.",
    selector: '[data-tutorial-target="create-subsystem-button"]',
  },
  {
    id: "edit-subsystem",
    title: "Edit a subsystem",
    instruction: "Click the subsystem edit icon.",
    selector: '[data-tutorial-target="edit-subsystem-button"]',
  },
  {
    id: "create-mechanism",
    title: "Add a mechanism",
    instruction: "Use Add mechanism and save it.",
    selector: '[data-tutorial-target="create-mechanism-button"]',
  },
  {
    id: "edit-mechanism",
    title: "Edit a mechanism",
    instruction: "Click a mechanism edit icon.",
    selector: '[data-tutorial-target="edit-mechanism-button"]',
  },
  {
    id: "add-part-to-mechanism",
    title: "Add a part to a mechanism",
    instruction: "Use the Add part button on a mechanism and save it.",
    selector: '[data-tutorial-target="add-part-to-mechanism-button"]',
  },
  {
    id: "manufacturing-tab",
    title: "Open Manufacturing",
    instruction: "Open Manufacturing from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-manufacturing"]',
  },
  {
    id: "manufacturing-cnc",
    title: "Open CNC queue",
    instruction: "Switch Manufacturing to CNC.",
    selector: '[data-tutorial-target="manufacturing-view-cnc"]',
  },
  {
    id: "create-cnc-job",
    title: "Add CNC job",
    instruction: "Use Add and save one CNC job.",
    selector: '[data-tutorial-target="cnc-create-job-button"]',
  },
  {
    id: "inspect-cnc-job",
    title: "Inspect a CNC job",
    instruction: "Click any CNC row to open the job editor.",
    selector: '[data-tutorial-target="cnc-edit-job-row"]',
  },
  {
    id: "manufacturing-prints",
    title: "Open 3D print queue",
    instruction: "Switch Manufacturing to 3D print.",
    selector: '[data-tutorial-target="manufacturing-view-prints"]',
  },
  {
    id: "create-print-job",
    title: "Add 3D print job",
    instruction: "Use Add and save one 3D print job.",
    selector: '[data-tutorial-target="prints-create-job-button"]',
  },
  {
    id: "complete-print-job",
    title: "Complete a 3D print job",
    instruction: "Open a print job and save it with Complete status.",
    selector: '[data-tutorial-target="prints-edit-job-row"]',
  },
  {
    id: "manufacturing-search",
    title: "Search manufacturing queue",
    instruction: "Use the search box in the 3D print queue.",
    selector: '[data-tutorial-target="prints-search-input"]',
  },
  {
    id: "manufacturing-fabrication",
    title: "Open fabrication queue",
    instruction: "Switch Manufacturing to Fabrication.",
    selector: '[data-tutorial-target="manufacturing-view-fabrication"]',
  },
  {
    id: "create-fabrication-job",
    title: "Add fabrication job",
    instruction: "Use Add and save one fabrication job.",
    selector: '[data-tutorial-target="fabrication-create-job-button"]',
  },
  {
    id: "inspect-fabrication-job",
    title: "Inspect a fabrication job",
    instruction: "Click any fabrication row to open the job editor.",
    selector: '[data-tutorial-target="fabrication-edit-job-row"]',
  },
] satisfies InteractiveTutorialStep[];

export const operationsChapter = {
  id: "operations",
  title: "Chapter 2: Build Operations",
  summary: "Roster, Inventory, Subsystems, and Manufacturing end-to-end.",
  preferredProjectType: "robot",
  steps: operationsSteps,
} satisfies InteractiveTutorialChapter;
